command_timeout = 5000

## info & status
[username]
format = " [â•­â•´](bold green)[$user]($style) in "
style_user = "bold green"
style_root = "bold green"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold green"
trim_at = "-"
ssh_only = false
disabled = true

# Third param
[directory]
style = "bold green"
truncation_length = 3
truncate_to_repo = true


# Before all the version info (python, nodejs, php, etc.)
[git_branch]
symbol = "ï˜ "
style = "green italic bold"
format = "on [$symbol$branch]($style) "
truncation_length = 10
truncation_symbol = ".../"


[git_status]
format = '[\($all_status$ahead_behind\)](bold italic green) '
conflicted = "ó°‡ "
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ó°— "
modified = "ï„ "
staged = '[+$count](green)'
renamed = "ó°–· "
deleted = "ï€” "

# Last param in the first line/row
[cmd_duration]
min_time = 3
format = "took [$duration]($style)"
disabled = true

[character]
# success_symbol = " [â•°â”€ ïŒƒ ](bold green)"
# error_symbol = " [â•°â”€ ïŒƒ ](bold green)"
success_symbol = " [â•°â”€ îœ‘](bold green)"
error_symbol = " [â•°â”€ îœ‘](bold green)"
# use_symbol_for_status = true

[conda]
symbol = "ï„Œ "
format = "[$symbol$environment](green) "
ignore_base = false
disabled = false

[python]
symbol = "î˜† "

[rlang]
symbol = "î·  "

[docker_context]
symbol = "ğŸ³ "
format = "via [$symbol$context]($style) "
style = "green italic bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false
