
## FIRST LINE/ROW: Info & Status
[username]
format = " [â•­â•´](bold red)[$user]($style) in "
style_user = "bold red"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style) in "
style = "bold red"
trim_at = "-"
ssh_only = false
disabled = true

# Third param
[directory]
style = "bold blue"
truncation_length = 0
truncate_to_repo = true

# Before all the version info (python, nodejs, php, etc.)
[git_branch]
symbol = "ï˜ "
style = "blue italic bold"
format = "on [$symbol$branch]($style) "
truncation_length = 10
truncation_symbol = ".../"

[git_status]
format = '[\($all_status$ahead_behind\)](bold italic blue) '
conflicted = "ó°‡ "
up_to_date = "ï† "
untracked = "ï”© "
ahead = "â‡¡${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "â‡£${count}"
stashed = "ó°— "
modified = "ï„ "
staged = '[+$count](blue)'
renamed = "ó°–· "
deleted = "ï€” "

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = "took [$duration]($style)"
disabled = false

# Prompt: param 2 â””â”€
[character]
success_symbol = " [â•°â”€ îœ‘](bold red)"
error_symbol = " [â•°â”€ îœ‘](bold red)"
# use_symbol_for_status = true

[aws]
symbol = "îŒ½ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ğŸ³ "
format = "via [$symbol$context]($style) "
style = "blue italic bold"
only_with_files = true
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_folders = []
disabled = false

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î˜Ÿ "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
disabled = true

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "î‰ "

[package]
symbol = "ï£– "

[perl]
symbol = "î© "

[php]
symbol = "î˜ˆ "

[python]
symbol = "î˜† "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[swift]
symbol = "ï¯£ "


# format = """\
# [â•­â•´](bold green)$username$os\
# $all[â•°â”€](bold green)$character"""
#
# [character]
# success_symbol = "[>](120)"
# error_symbol = "[>](120)"
#
# [os]
# format ='[$symbol](bold yellow)'
# disabled = false
#
# # [os.symbols]
# # Macos = 'ï£¿ '
#
# [username]
# style_user = "green bold"
# format = "[ Minh's ï…¹ ](yellow bold)"
# show_always = true 
#
# [cmd_duration]
# min_time = 4
# show_milliseconds = false
# disabled = false
# style = "bold italic red"
#
# [python]
# symbol = "ó°Œ  "
# python_binary = "python3"
# format = "using [$symbol$version]($style) "
# style = "bold blue italic"
#
# [conda]
# format = 'via [$symbol$environment](bold italic blue) '
#
# [directory]
# read_only = " ï€£ "
# truncation_length = 10
# truncation_symbol = ".../"
# home_symbol = "~"
# truncate_to_repo = true # truncates directory to root folder if in github repo
# style = "bold italic blue"
# format = "in [$path]($style)[$read_only]($read_only_style) "
#
# [nodejs]
# disabled = true
#
#
# [git_branch]
# symbol = "ï˜ "
# style = "blue italic bold"
# format = "on [$symbol$branch]($style) "
# truncation_length = 10
# truncation_symbol = ".../"
#
# [git_status]
# format = '[\($all_status$ahead_behind\)](bold italic blue) '
# conflicted = "ó°‡ "
# up_to_date = "ï† "
# untracked = "ï”© "
# ahead = "â‡¡${count}"
# diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
# behind = "â‡£${count}"
# stashed = "ó°— "
# modified = "ï„ "
# staged = '[+$count](blue)'
# renamed = "ó°–· "
# deleted = "ï€” "
#
# [lua]
# disabled = true
#
#
# [docker_context]
# symbol = "ğŸ³ "
# format = "via [$symbol$context]($style) "
# style = "blue italic bold"
# only_with_files = true
# detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
# detect_folders = []
# disabled = false

